require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'config/initializers/devise.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Exclude:
    - 'config/**/*'
    - 'spec/rails_helper.rb'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false